### ISSUE TITLE
very different generated DSLs in development and CI

### ISSUE THREAD

**Issue by BrianHicks** [Shopify/tapioca#1013]
Hey there! I'm using Tapioca 0.8.2 and trying to set up a `tapioca dsl --verify` check in CI. Problem is, even when I set `RAILS_ENV=development` Tapioca generates hugely different signatures in CI! I'm not sure how to debug this, though… what could I provide that could help? Or, does this sound like a normal thing that you just know about?

**Comment by BrianHicks** [comment]
OK, so I was typing that as I was heading out the door yesterday and I think I can provide a few more details:

- my dev machine is a M1 Mac, the build servers are Linux (NixOS, specifically, in a container.)
- the differences fall into two buckets:
  - methods are ordered differently in the two environments (looks like this comes mostly from a custom DSL compiler)
  - nilability changes in AR models, like so:

```diff
-    sig { returns(T.nilable([::Integer, ::Integer])) }
+    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
     def saved_change_to_writing_sample_id; end
```

**Comment by Morriar** [comment]
> Is that in a released version? 

Indeed it still is unreleased, we should have a 0.9 version shortly.

> does it not do the same thing?

Sorry I misread your question, yes it does.

> It's down to the nilable changes now

Is it possible that the database is not in the same state on both environments?

**Comment by BrianHicks** [comment]
> Is it possible that the database is not in the same state on both environments?

Yes, this is possible. I updated by merging in the latest main branch, and the problem went away (despite requiring no DSL updates.) I hope it is not magical thinking to think I've solved the problem! Once the check goes in, I imagine the merging problems may be somewhat lessened.

**Comment by KaanOzkan** [comment]
@ric2b I'm seeing extra "`" characters on those added lines. Is this just the diff format or are the method definitions actually have that prefix for some reason?

If not this is strange because they are supposed to be sorted before being outputted to a file https://github.com/Shopify/rbi/blob/2d0e0143212c5ae8be0692add8f1c657220e34e1/lib/rbi/formatter.rb#L63.

I think you should create a new issue since ordering is a different problem and you're specifying the environment flag.
