### ISSUE TITLE
Are the dependencies too broad?

### ISSUE THREAD

**Issue by will** [Shopify/tapioca#1052]
Do things pry and thor need to be full dependencies that users of tapioca also have to install, or can they be development dependencies?

**Comment by rafaelfranca** [comment]
Thank you for the issue.

No, they are not.

Thor is required since it is how the tapioca CLI is defined https://github.com/Shopify/tapioca/blob/55cc72f6e052b90df78e8a3f0190a62dce88efc3/lib/tapioca/cli.rb.

`pry` is used to find which file defines a constant https://github.com/Shopify/tapioca/blob/55cc72f6e052b90df78e8a3f0190a62dce88efc3/lib/tapioca/gem/pipeline.rb#L356. We probably could reimplement that, but I don't think we have a reason to do that right now.

Is there any concern that caused you to open the issue?

**Comment by will** [comment]
I no longer needed pry for my project since the newer versions of irb do everything I used to use pry for. I was surprised when removing it from my gemfile that it was still one of my dependencies.
