### ISSUE TITLE
New gem has segmentation fault when doing `bundle exec tapioca init`

### ISSUE THREAD

**Issue by JoshRudnik** [Shopify/tapioca#1061]
When creating a brand new gem with bundler and using tapioca, a segfault with memory trace occurs.

Original error:
```
/Users/josh.rudnik/.rvm/gems/ruby-3.0.0/gems/tapioca-0.9.0/lib/tapioca/gem/listeners/methods.rb:158: [BUG] Segmentation fault at 0x0000000000000010
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21]
```

Steps to reproduce:
1. Make new gem: `bundle gem test && cd test`
2. Add `gem 'tapioca', require: false` to Gemfile
3. `bundle install`
4. `bundle exec tapioca init`

Ruby version:
`ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21]`

Ruby diagnostic crash report is attached (as a zip file since you can't directly upload `.ips` files)
[ruby-2022-07-13-133538.ips.zip](https://github.com/Shopify/tapioca/files/9104996/ruby-2022-07-13-133538.ips.zip)

**Comment by paracycle** [comment]
Actually, I think I know what's happening here and it is not about M1 at all.

Here is the problem: https://bugs.ruby-lang.org/issues/18329

Basically, there was a bug in Ruby where if you called `super_method` on a method object which didn't have a super method defined, then it would crash Ruby. The fix for this was backported to Ruby 3.0 and was released as part of Ruby 3.0.3, so you should be on that version or above.

Btw, Ruby 3.0 was a particularly unstable release and it had really big problems until Ruby 3.0.3 (including a big memory leak in 3.0.2), so I highly suggest that you move your workloads to the latest version of Ruby 3.0 or even better to Ruby 3.1 (which is way more stable) as soon as possible.
