### ISSUE TITLE
Use Rails relations in typing

### ISSUE THREAD

**Issue by Overload119** [Shopify/tapioca#1140]
My ActiveRecord model is Person.

```rb
sig { params(blck: T.proc.params(people: Person::PrivateRelation).void).void }
def foreach_matching_person_query(&blck)
  # ...
  yield(Person.joins(:companies))
end
```

I have something like this - it throws no errors in Sorbet. 
In runtime, it throws:

```rb
NameError: uninitialized constant Person (call 'Person.connection' to establish a connection)::PrivateRelation
```

How can I properly type this?

The query itself is `Person::ActiveRecord_Relation` but this is a private class I believe. Sorbet can't read it.

**Comment by G2Jose** [comment]
I ended up creating an initializer that at runtime creates these classes that tapioca RBI references. This is what it looks like: 

```ruby
# config/initializers/sorbet.rb
ActiveRecord::Base.descendants.each do |klass|
  klass.const_set('PrivateAssociationRelation', Object)
  klass.const_set('PrivateAssociationRelationWhereChain', Object)
  klass.const_set('PrivateCollectionProxy', Object)
  klass.const_set('PrivateRelation', Object)
  klass.const_set('PrivateRelationWhereChain', Object)
end
```

Would love to see if there's a better way.

**Comment by rafaelfranca** [comment]
See the `CAUTION` on this document https://github.com/Shopify/tapioca/blob/main/manual/compiler_activerecordrelations.md

**Comment by timfjord** [comment]
The suggestion above does fix the issue, but only partly.  
Because, it is still not clear how to properly work with class methods/scopes defined in the model itself.

Even in the example, what if we need to call a specific scope from the `Person` model
```ruby
class Person < ApplicationRecord
  # ...

  scope :active, -> { where(active: true) }
end

# ...

sig { params(blck: T.proc.params(people: ActiveRecord::Relation).void).void }
def foreach_matching_person_query(&blck)
  # ...
  yield(Person.joins(:companies))
end

foreach_matching_person_query do |people|
  puts people.active.count
end
```

Sorbet won't like this because we are trying to call it `active`, but it thinks `people` is an instance of `ActiveRecord::Relation`, so it will complain that the method doesn't exist

**Comment by G2Jose** [comment]
> Sorbet won't like this because we are trying to call `active` on the `people`, but it thinks `people` is an instance of `ActiveRecord::Relation`, so it will complain that the method doesn't exist

Exactly - this is why I resorted to making these private constants public using `const_set`. 

Wish there were a less hacky, more idiomatic way to get this working.

**Comment by CodingAnarchy** [comment]
I would concur and suggest this ticket should be reopened. We just ran into a case where we added a scope and Sorbet blew up a ton of type checks precisely because `ActiveRecord::Relation` is not the specific type in question. `sorbet-rails` makes the private constants public similar to @G2Jose did above, and then type aliases them in a bundle. Tapioca just breaks on it, currently.

**Comment by fazo96** [comment]
I am facing the same problem, and the workaround by @timfjord doesn't seem the work. The constants stay undefined at runtime.

Using `ActiveRecord::Relation` as type means we have type errors if we try to call scopes on them, so we are forced to keep these values as `T.untyped` losing out not just the type checks but also the IDE integration via language server.

Overall this seems like a major problem and I would re-open this issue

Is there another solution to specify the type? There is some work in https://github.com/Shopify/tapioca/pull/1476 but I wasn't able to find any follow up from @georgebrock

**Comment by rex-remind101** [comment]
`T::Sig::WithoutRuntime.sig` doesn't seem to be an option when you're performing a `T.let(<expression>, PrivateRelation)`

**Comment by ebarajas** [comment]
+1 I think this should be re-opened. We're in the middle of trying to move off of `sorbet-rails` and onto tapioca and this is a pretty sizeable blocker. 

Curious to hear what Shopify does in this situation, is it really just returning `T.untyped` instead?

**Comment by deecewan** [comment]
we've got a similar solution to @G2Jose and it's working fine for us

**Comment by bmulholland** [comment]
Should that solution be an official recommendation, then?

**Comment by marknuzz** [comment]
Instead of `sig { params(blck: T.proc.params(people: ActiveRecord::Relation).void).void }` suggested by Rafael, would this work?

`sig { params(blck: T.proc.params(people: T.all(T::Enumerable[Person], ActiveRecord::Relation)).void).void }`

**Comment by stathis-alexander** [comment]
I did this
```ruby
ActiveSupport.on_load(:active_record) do
      module AciveRecordInheritDefineRelationTypes
        def inherited(child)
          super(child)

          # Tapioca defines these three classes for each active record model as proxies for the actual AR internal
          # classes. In order to be able to use these as types in signatures, we need to expose them as actual constants
          # at runtime. Tapioca intentionally obfuscates these classes because they're private, so exposing them is
          # _slightly_ dangerous in that someone could do something naughty. But we're not super worried about it.
          child.const_set("PrivateRelation", child.const_get(:ActiveRecord_Relation))
          child.const_set("PrivateAssociationRelation", child.const_get(:ActiveRecord_AssociationRelation))
          child.const_set("PrivateCollectionProxy", child.const_get(:ActiveRecord_Associations_CollectionProxy))

          # Expose a common type so that signatures can be typed to the broader `RelationType` since the three are often
          # used interchangeably.
          relation_type = T.type_alias do
            T.any(
              child.const_get(:PrivateRelation),
              child.const_get(:PrivateAssociationRelation),
              child.const_get(:PrivateCollectionProxy),
            )
          end
          child.const_set(:RelationType, relation_type)
        end
      end

      class ::ActiveRecord::Base
        class << self
          prepend AciveRecordInheritDefineRelationTypes
        end
      end
    end
```
which works pretty well. Type checking is actually a bit more precise than the earlier solution, since, for instance, a method like this:
```ruby
sig { params(author: Author).returns(Post::PrivateAssociationRelation) }
def recent_posts_from_author(author)
  Post.where(author: author).where('created_at > ?', 1.week.ago)
end
```
will actually emit a Sorbet error since a `Post::ActiveRecord_Relation` class is returned. 

In addition, I've included the `RelationType` union type, and added a compiler to our [Boba](https://github.com/angellist/boba) gem to generate the corresponding RBIs, so that you can use the union type. This way, you can type your returns / arguments to be as precise as you might like.

**Comment by marcus-deans** [comment]
The [Boba](https://github.com/angellist/boba/) gem may be of interest, specifically the ActiveRecordRelationTypes` [compiler](https://github.com/angellist/boba/blob/main/lib/tapioca/dsl/compilers/active_record_relation_types.rb).

I only recently found this gem from the bottom of the Tapioca docs, but it seems likely to be helpful in adopting Sorbet more fully in a Rails context. I concur that this should be a core Tapioca feature regardless though, rather than relying on an external compiler

**Comment by bitterepic** [comment]
This comment was maid around when I was having problems getting Tapioca to load sorbet plugins.  If I came back to it, I would probably do this.  In particular, not enforcing  the local gems execution with bundler caused all sorts of weird errors (that I may have had some warnings in the CLI about)
