### ISSUE TITLE
tapioca rbi - URI::File of URI::Source does not derive from Class

### ISSUE THREAD

**Issue by denvermullets** [Shopify/tapioca#1154]
Note: this is a Rails API

i added a couple of gems (bcrypt / jwt, if you're curious) and then updated my tapioca gem (0.10.0). now i am getting this in the Todo file and shows up when running `srb tc`

```ruby
sorbet/rbi/gems/tapioca@0.10.0.rbi:3030: The super class URI::File of URI::Source does not derive from Class https://srb.help/5067
    3030 |class URI::Source < ::URI::File
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sorbet/rbi/todo.rbi:8: URI::File defined here
     8 |module URI::File; end
        ^^^^^^^^^^^^^^^^
Errors: 1
```

i deleted the sorbet folder and re-initialized everything and it comes back. 

here's my gemfile if that helps:

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

ruby '3.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.0.3.1'

gem 'bcrypt', '~> 3.1.7'
gem 'httparty'
gem 'jwt', '~> 2.2'
gem 'pg', '~> 1.1'
gem 'pry-byebug'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rubocop'
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development

gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end
```

certainly not a blocker for me but figured i'd mention it if there was a command i missed or something!

**Comment by Morriar** [comment]
Hey @denvermullets,

As explained in the [documentation](https://github.com/Shopify/tapioca#:~:text=This%20will%20generate%20the,committed%20in%20your%20repository.), The `sorbet/rbi/todo.rbi` file is used to define all unresolved constants as empty modules. Since the constants are "missing", Tapioca does not know if they should be marked as modules or classes and will use modules as a safer default. This file should be reviewed, corrected, if necessary, and then committed in your repository.

You should go over the contents of this file, remove any unnecessary constants and move the other ones to proper shims under `sorbet/rbi/shims/`. Note that, sometimes, constants are missing because of [missing requires](https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem). Ideally you should be able to remove this file all together.

**Comment by denvermullets** [comment]
ok, word, i'll poke around. thanks for the update
