### ISSUE TITLE
Adding "debug" gem generates typing error in RBI file

### ISSUE THREAD

**Issue by olivierlabreche** [Shopify/tapioca#1276]
This ServicesDB [PR](https://github.com/Shopify/services-db/pull/15756) attempts to add "debug" to dependencies.

After regenerating RBIs, this [Sorbet CI check](https://buildkite.com/shopify/services-db/builds/49569#01848bf3-f28b-41e8-9f62-74e6d154520f) fails with this error message:
```
sorbet/rbi/gems/irb@1.4.1.rbi:2013: Parent of class IRB::ReidlineInputMethod redefined from IRB::RelineInputMethod to IRB::InputMethod https://srb.help/5012
    2013 |class IRB::ReidlineInputMethod < ::IRB::InputMethod
                                           ^^^^^^^^^^^^^^^^^^
Errors: 1
```

## What I tried
- generating all RBIs with `dev rbi-all`
- adding `irb` to `sorbet/tapioca/require.rb`

These did not fix the typing error.

**Comment by KaanOzkan** [comment]
You need to bump to a `sorbet-static-and-runtime` version that includes https://github.com/sorbet/sorbet/commit/c2b8c56cc5d24ca8ac46e323f5be3c7ecf9513b8. That's compatible with the correct RBIs that tapioca generates.

In situations like this I'd advise finding the other definition for your constant. Since IRB is part of the standard library its RBIs are shipped with Sorbet which contained an outdated parent class.

**Comment by olivierlabreche** [comment]
Thanks, that seems indeed to be the right fix but running into other [typing errors](https://github.com/Shopify/services-db/pull/15756#issuecomment-1322718981). Will continue the convo on that repo!

> You need to bump to a `sorbet-static-and-runtime` version that includes [sorbet/sorbet@c2b8c56](https://github.com/sorbet/sorbet/commit/c2b8c56cc5d24ca8ac46e323f5be3c7ecf9513b8). That's compatible with the correct RBIs that tapioca generates.
> 
> In situations like this I'd advise finding the other definition for your constant. Since IRB is part of the standard library its RBIs are shipped with Sorbet which contained an outdated parent class.

**Comment by KaanOzkan** [comment]
Yes it's expected. I jumped the gun earlier and assumed you were on the latest `irb`. However, dependabot bumped your Sorbet version to include my fix above. So incompatibility came from Sorbet version being too new.

Sorbet only supports one set of internal standard library RBIs. As a result it aims to be compatible with the latest version of the stdlib. You currently can't tie Sorbet versions to a specific gem version. They are coupled due to RBI generation however, they are different gems with no dependencies to each other. 

I think best solution is for the error message to be clear and tell the users that there are 2 sets of RBIs for stdlib. Currently it only shows a single source which is confusing. Tapioca RBIs reflect the runtime behaviour so in these cases they will be correct for the gem version you are using.
