### ISSUE TITLE
Association lambdas have wrong relation type

### ISSUE THREAD

**Issue by grncdr** [Shopify/tapioca#1515]
Given the following code:

```rb
# app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user 
  scope :not_deleted, -> { where(deleted_at: nil) }
end
```

```rb
# app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, -> { not_deleted } # error: Method `not_deleted` does not exist on `User::PrivateRelation`
end
```

To work around it one has to write this instead:

```rb
has_many :posts, -> { T.bind(self, Post::PrivateRelation); not_deleted } # OK
```

To be honest I'm not sure that Sorbet can express this sort of dependent typing. It would also be interesting if Tapioca could somehow "inject" the `T.bind` but that's probably way too intrusive.

**Comment by paracycle** [comment]
Hi @grncdr, apologies for the late response here. What you are pointing out is a side-effect of how Ruby lambdas work and how Sorbet can deal with them. 

Since lambdas are first-class Ruby objects, they can be passed around freely. However, for any given lambda, it can be called multiple times with a different `self` for each invocation. So, in general, there is no de facto definition of `self` for a given lambda, just that there is a default. What Sorbet does is to assume that default for the value of `self`, which happens to be the value of `self` in the scope that the lambda was defined in. In your examples, since the lambdas are defined in a class context, they assume `self` to be the class, which would be `T.class_of(User)` in your example (coincidentally, the error you'd be getting is probably ```# error: Method `not_deleted` does not exist on `T.class_of(User)` ``` and not ```# error: Method `not_deleted` does not exist on `User::PrivateRelation` ```).

Here is an example of what I mean:
```ruby
class Foo
  LAMBDA = -> do 
    # is there a stable `self` for this block?
    puts self
  end

  def call_lambda
    # this should show the default `self`
    LAMBDA.call
  end

  def call_lambda_with_instance_exec
    # this should change the value of `self` inside the block
    instance_exec(&LAMBDA)
  end
end

foo = Foo.new
foo.call_lambda # => Foo
foo.call_lambda_with_instance_exec # => #<Foo:0x0000000104eda878>
```

There is no way for any code, Sorbet nor Tapioca, to know for certain how the lambda will be called, except for the specific method that the lambda is passed to. That is, only the author of the lambda call can make an assertion about the body of the lambda based on which methods are using it, and how does methods call the lambda.

For this reason, there is nothing Tapioca can do in this case. Moreover, even if it were possible to tell what `T.bind` should be inserted into the body of the lambda, Tapioca deals purely with RBI files and does not make any changes to the application code, so it wouldn't be able to insert any code anyway.

**Comment by grncdr** [comment]
Yes, I agree this is more or less a deficiency in Sorbet vs. Tapioca itself. It's annoying that you _can_ annotate the binding type for block parameters, but **only** block parameters (and not lambdas), but oh well. 🤷‍♂️
