### ISSUE TITLE
Tapioca generates methods as override when abstract definitions aren't loaded

### ISSUE THREAD

**Issue by KaanOzkan** [Shopify/tapioca#1562]
Latest version of spoom (1.2.2) has an [example of this](https://github.com/Shopify/spoom/blob/012ad244e0d7a524f91b7c74d3fa29e0cbc467ac/lib/spoom/deadcode/indexer.rb#L33-L34) because `syntax-tree` gem doesn't load necessary definitions by default and the abstract definitions are omitted. Upon generating the RBIs for spoom the signatures cause typechecking errors. We could improve the UX by:

- Omitting the signatures unless abstract definitions are present
- Improve loading logic, `tapioca require` to fix the root cause

Current workaround: manually requiring the gem (in this case `require "syntax_tree"`) in `sorbet/tapioca/require.rb` and running `bin/tapioca gem syntax_tree`.

**Comment by Morriar** [comment]
> Omitting the signatures unless abstract definitions are present

Since we allow generating RBIs in isolation, I'm not sure this would be possible without adding a new mechanism to load the RBIs already generated and do some checks.

> Improve loading logic, tapioca require to fix the root cause

Yeah I think it's the best approach. We can assume that the parent method must exist or else the signature would be plain wrong. If we don't find the parent method it's then most likely that we didn't require the proper dependencies.

**Comment by paracycle** [comment]
This is not a loading problem, it is a side-effect of the lightweight `tapioca gem` command that assumes it can handle gem version changes or addition/deletions on their own.

This fails for the cases where a gem pulls in a new dependency on a gem that already has an RBI generated, like `spoom`. Since `spoom` code does a `require "syntax-tree"`, classes and methods would be loaded just fine and Tapioca would generate the relevant entries for the abstract methods inside Syntax Tree. However, since `tapioca gem` command can only see that the `spoom` gem version has changed, then it only tries to generate an RBI for `spoom`, and not `syntax-tree`. If the previous `syntax-tree` RBI file did not have a definition for these abstract methods, then they would not be added either.

So, the root cause is not related to loading or `tapioca require`, but it is due to the way we do the lightweight "gem sync" operation. This would be resolved if one ran a `bin/tapioca gem --all` command even without the `require.rb` addition.

One idea to work around this is, when generating RBI for a gem `X`, to track references from code in `X` to constants that are not defined in `X`, and then to queue gem RBI generation for gems that contain those constants as well. That would have solved this problem, since `Spoom::DeadCode::Indexer` subclasses from `SyntaxTree::Visitor`, which would have triggered a gem RBI regeneration for the `syntax-tree` gem.
