### ISSUE TITLE
How to use `GeneratedPathHelpersModule`?

### ISSUE THREAD

**Issue by aergonaut** [Shopify/tapioca#172]
Hi Tapioca team!

I recently learned about Tapioca from watching Shopify's Shipit! presentation on adopting Sorbet. I was very interested to try it out as my team and I have tried to adopt Sorbet on our large Rails projects in the past but have run into various complications.

First off, I'm happy to say that using Tapioca was much smoother than using Sorbet's built-in tooling! Adding it to a small project went almost entirely smoothly, whereas I could not get past the initial setup with the built-in tools. Thank you for this project!

I do have 1 question, however. In the [UrlHelpers](https://github.com/Shopify/tapioca/blob/master/manual/generator_urlhelpers.md) docs, it says a `GeneratedPathHelpersModule` is generated and included into the RBI for any class that includes the dynamic URL helpers module. I see that module is generated in an RBI file, and it is included in the RBI file for my classes.

My question then: How do I use the `GeneratedPathHelpersModule` module in my class?

Sorbet of course complains about the dynamic `include Rails.application.routes.url_helpers`, so I need to replace that with something.

But `GeneratedPathHelpersModule` only exists in the RBI files, so I cannot use `include GeneratedPathHelpersModule`. I get a NameError when I try that.

How do I replace `include Rails.application.routes.url_helpers`?

**Comment by KaanOzkan** [comment]
Glad you're enjoying tapioca!

Yes you are correct about the `UrlHelpers` generator but you don't need to actively include `GeneratedPathHelpersModule` in your code. That module contains declarations of methods available to you at runtime. This is so that Sorbet "knows about" those methods during its static type check.  It's enough for it to be used in the generated `.rbi` file for Sorbet to know about its methods. 

`include Rails.application.routes.url_helpers` is a separate issue. It's a runtime include and therefore Sorbet doesn't know about it as you said. You can just use `T.unsafe` while including it to workaround the problem.

`T.unsafe(self).include(Rails.application.routes.url_helpers)`

We will update the generator docs to use `T.unsafe` as well so it's more clear. Thanks for opening this issue.

**Comment by aergonaut** [comment]
Thanks @KaanOzkan! That worked.

**Comment by paracycle** [comment]
@aergonaut I added a note on the example code in the [UrlHelpers doc](https://github.com/Shopify/tapioca/blob/master/manual/generator_urlhelpers.md) that should make the intended use-case clearer. Does that help?

**Comment by aergonaut** [comment]
@paracycle Yes, that helps. Thank you!

**Comment by danjcosg** [comment]
Hey, I'm still seeing this error when running `srb tc`:

> include must only contain constant literals https://srb.help/4002
    37 |  include Rails.application.routes.url_helpers

It'd be nice to at least have an error message with the suggested workaround!
