### ISSUE TITLE
Rails engines with tapioca does not seems to work

### ISSUE THREAD

**Issue by troptropcontent** [Shopify/tapioca#1766]
Hello ✋ 

Happy new year :) 

I am creating a new rails engine and i would like to setup sorbet on it from the beggining. 

I did `rails plugin new` , then i added :

- `spec.add_dependency "rails", ">= 7.1.2"` in my plugin.gemspec
- `gem "sorbet", "~> 0.5.11193", group: :development`  in my plugin Gemfile
- `gem "tapioca", "~> 0.11.17", require: false, group: [:development, :test]`  in my plugin Gemfile

Then i wanted to run `bundle exec tapioca init` but it throws the following error :

![image](https://github.com/Shopify/tapioca/assets/75135824/5516f47b-36a6-419e-858c-1bc13817b25d)

Does anyone already achieve this ?

I really have no clue on this but it seems that tapioca does not see that it needs to look for rails as it is not directly contained in Gemfile but in the plugin.gemspec dependancies, i tried to put rails temporarily in the gemfile, the tapioca init worked but then the tapioca dsl does not work for new models, i might miss something

Thank you so much for your help

Best 
Tom

**Comment by paracycle** [comment]
You are asking a few questions here that need to be answered separately:

1. The error you are seeing with the `tapioca gem` step is happening because no one has called `require "rails"` ever, so as that file is being loaded the constant `Rails` is not defined. Adding `rails` as a runtime dependency just ensures that whoever is installing your engine has `rails` as part of gem bundle as well. But, if your gem has not required `rails` itself, then no one would be magically requiring it. This is different to when you put `gem "rails"` in your `Gemfile`, which, by default, automatically requires the gem as well (unless you also pass `, require: false`).
   Btw, for an engine, the best thing to do is to: (1) `require 'finance/engine' if defined?(Rails::Engine)` so that the engine is never loaded if one loads your gem in a non-Rails context (you can see [many examples of this in engines](https://github.com/search?q=defined%3F%28Rails%3A%3AEngine%29&type=code) and a similar thing is documented for Railties (which is the parent class of `Engine`) [here](https://github.com/rails/rails/blob/25b7f640749e0dbbf731a7f5696e5c785195f922/railties/lib/rails/railtie.rb#L46)) and (2) to not explicit require Rails or anything in the Rails framework as part of your gem, but [to use lazy load hooks to do your initialization](https://simonecarletti.com/blog/2011/04/understanding-ruby-and-rails-lazy-load-hooks/).
   So, how can you get Tapioca to load this file properly? Well, you can add a `require "rails"` in the `sorbet/tapioca/require.rb` file to load Rails while Tapioca is loading your gem and its dependencies. This is documented in the [README](https://github.com/Shopify/tapioca?tab=readme-ov-file#manually-requiring-parts-of-a-gem).
2. `tapioca dsl` will NOT work with engines out of the box, since that command only knows how to load a Rails application so far. This restriction is tracked in [this issue](https://github.com/Shopify/tapioca/issues/442). You can load your engine in a `sorbet/tapioca/compilers/load.rb` file, but that alone won't be enough since an engine alone does not define a database connection, etc, which is needed to figure out what attributes a model has. In order to do that properly, you will need to load the dummy Rails app that you are probably using to test your engine while the DSL run is happening.
