### ISSUE TITLE
RBI generated for ActiveModel with custom types seems to be incorrect

### ISSUE THREAD

**Issue by mihyaeru21** [Shopify/tapioca#1771]
The RBI generated by `tapioca dsl` seems to be incorrect when using ActiveModel::Attributes with custom types. Here is an example.

```ruby
require 'active_model'
require 'uri'

class UriType < ActiveModel::Type::Value
  private

  def cast_value(value)
    URI.parse(value) # the return type is URI::Generic
  end
end

class Foo
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :uri, UriType.new
end

Foo.new(uri: 'https://example.com/').uri.hostname
#=> 'example.com'
```

In this case, the return type of `Foo#uri` is expected to be `T.nilable(URI::Generic)`. But in actuality, it is `T.nilable(UriType)`. The `UriType` which extends `ActiveModel::Type::Value`, does not represent the `URI::Generic` itself, but the type of the attribute in ActiveModel. Just as `ActiveModel::Type::Integer` is not `Integer`.

This change was introduced in #1715 and is included in v0.11.15 and later versions. Newer versions of tapioca are no longer usable in projects that use custom types because type errors cannot be avoided. I think this change needs to be revert and implemented differently.

**Comment by KaanOzkan** [comment]
One solution to support `cast_value` could be looking for a `cast_value` method definition on the type and if it exists we grab the return type from its signature.  If there's no signature we type it as `T.untyped`.

**Comment by jscheid** [comment]
Thanks @mihyaeru21, this is a great improvement.

It doesn't quite go far enough for my use case though. I have a helper method that generates custom subclasses of `ActiveModel::Type::Value` at runtime. Because of this I can't set `sig`s.

Would it be possible to add some way to specify the expected return value at runtime? Maybe a class method (on the `ActiveModel::Type::Value` subclass) named `value_type` that is invoked if present? Or maybe `rbi_type` to make conflict with future Rails versions less likely.
