### ISSUE TITLE
DSL support for rails 4?

### ISSUE THREAD

**Issue by pascalmail** [Shopify/tapioca#181]
Hi, tapioca team.

I recently tried running `tapioca dsl` using it on my apps (rails v 4.2.7.1), but got error:
```
.../gems/tapioca-0.4.10/lib/tapioca/loader.rb:112:in eager_load_rails_app': undefined method `autoloaders` for Rails:Module (NoMethodError)
```

I then commented the line, but it fails again at 
```
gems/activerecord-4.2.7.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `generated_relation_methods' for #<Class:0x007fea82ab89d8> (NoMethodError)
```

It looks like rails 4 do not have `generated_relation_methods`.

Can you add support rails 4? Thanks!

**Comment by paracycle** [comment]
Hello @pascalmail, thank you for trying Tapioca on your application. We are aware that there are many projects that are still on older versions of Rails, however, any version of Rails before 5.2 [is not supported by the Rails team anymore](https://guides.rubyonrails.org/maintenance_policy.html). We try to stay in-line with this policy, since we don't have the resources to keep older versions of Rails supported.

However, if you would like to contribute a PR to support older versions of Rails and then support it going forward, we would definitely be interested in helping you do it. Let us know if that is something you want by reopening this issue.
