### ISSUE TITLE
Declaring a class method called "hash" leads to an unhelpful error

### ISSUE THREAD

**Issue by hlascelles** [Shopify/tapioca#191]
We had a class declaration like this:

```
class FooTest
  class << self
    def hash
      @hash ||= {}
    end
  end
end
```

When we ran Tapioca on it, we saw this:

```
  Compiling foo_project, this may take a few seconds... bundler: failed to load command: tapioca (2.6.6/bin/tapioca)
TypeError: no implicit conversion of Hash into Integer
  ruby/2.6.0/set.rb:254:in `include?'
```

We found it comes from here: https://github.com/Shopify/tapioca/blob/3937c0a658e000f6881bec9827e219992af13f1f/lib/tapioca/compilers/symbol_table/symbol_generator.rb#L311

It is true that `Set.new.include?(FooTest)` blows up like that.

I was going to create a PR, but thought I'd check how you'd like to handle it first. Thanks!

**Comment by paracycle** [comment]
Oh, I see what is happening here, thanks for the detailed report. I'll see how we can fix this but, in the meanwhile, I would like to note that your method name choice is quite problematic.

Your `FooTest` class is overriding `Object#hash` in an incompatible way. Normally `Object#hash` is used to calculate a numeric hash key value which is used to figure out where to place the object in a `Hash` table. That is what makes `Hash` lookups efficient.

Your override is returning an `Hash` value from that method instead, so Ruby has difficulty using the class as a `Hash` key, and, in turn, as a `Set` value, since `Set`s are built using `Hash`es.

These would all fail:
```ruby
> Set.new([Foo])
TypeError: no implicit conversion of Hash into Integer
> { Foo => "bar" }
TypeError: no implicit conversion of Hash into Integer
> h = {}; h[Foo] = "bar"
TypeError: no implicit conversion of Hash into Integer
```

You should keep that in mind if you ever want to use the class as a `Hash` key at some point.

**Comment by hlascelles** [comment]
Yes, very fair point - we have now changed the name!

You may choose not to do anything about this. Maybe this issue can just be a documentation / pointer to [anyone who follows](https://xkcd.com/979/).

**Comment by paracycle** [comment]
> Yes, very fair point - we have now changed the name!

Awesome. That's a smart move against some future WTFs in your codebase. 😂 

> You may choose not to do anything about this. Maybe this issue can just be a documentation / pointer to [anyone who follows](https://xkcd.com/979/).

I would still like to fix this since Tapioca tries really hard to be resilient against all kinds of user manipulation of types. I mention some of the wild things libraries do that we had to protect against in my [RubyKaigi talk](https://www.youtube.com/watch?v=OJRQAn6BfpE).

PS: Nice touch with the XKCD link :)
