### ISSUE TITLE
attr_* signatures are not being extracted with `tapioca gem` with hand rolled types

### ISSUE THREAD

**Issue by ryanong** [Shopify/tapioca#2020]
POC

```ruby
# Gemfile

source 'https://rubygems.org'

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => [:development, :test]
gem 'pdf-reader'
```

```
$ tapioca init
$ tapioca gem pdf-reader
```

If you look in the extracted rbi file for pdf-reader you will see that none of the attr_reader methods have signatures

This might apply to all gems including ones with inline types

**Comment by amomchilov** [comment]
Hey Ryan! Your observations are exactly correct, and match this existing issue: #1918

I have some work-in-progress in #1936 which standardizes on always emitting `attr_*` methods as plain methods, so their types can be merged along with other plain methods like normal. I'm not sure when I'll be able to merge that, however.

For now, the temporary workaround is to write the gems' inline types using regular method syntax, instead of `attr_*`.
