### ISSUE TITLE
Capybara DSL module not loaded

### ISSUE THREAD

**Issue by wjwatkinson** [Shopify/tapioca#218]
I was updating rbis after Dependabot did its work, but now typechecking is failing. In the past I have deleted rbis and run dev update-rbis again to recreate them correctly, but that is not working.
https://buildkite.com/shopify/ihub/builds/188#935657fb-1e37-4d56-b057-dbf65456e8f0/208-209

I was pointed here from #help-kernel
https://shopify.slack.com/archives/C0140UXPTF0/p1612391336238100

**Comment by paracycle** [comment]
This is a problem with changes/updates in one gem affecting the includes/extends or other behaviour in another gem. When you regenerate the RBI for a single gem, it gets these new additions (like `include Capybara::DSL`) but since the other gem RBI is not generated, we can't generate the new constant in its own gem RBI (in this case `Capybara::DSL` which is expected to be in `sorbet/rbi/gems/capybara@3.35.3.rbi`).

The best course of action in these cases is to remove all RBI files and regenerate everything. I did just that on your repo and this is the output:
```console
$ rm -rf sorbet/rbi/gems/*.rbi

$ bundle exec tapioca sync
Removing RBI files of gems that have been removed:

  Nothing to do.

Generating RBI files of gems that are added or updated:

  Requiring all gems to prepare for compiling...    Done

  Compiling actioncable, this may take a few seconds...   Done
  ++ Adding: sorbet/rbi/gems/actioncable@6.1.1.rbi
  ...
  ...

All operations performed in working directory.
Please review changes and commit them.

$ bin/srb tc
sorbet/rbi/gems/webrick@1.7.0.rbi:187: Method WEBrick::HTTPAuth::Htpasswd#initialize redefined without matching argument count. Expected: 1, got: 2 https://srb.help/4010
     187 |  def initialize(path, password_hash: T.unsafe(nil)); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/d96fcfd86b01b882822d432a9d771c60e7c7afc5/rbi/stdlib/webrick.rbi#L1360: Previous definition
    1360 |  def initialize(path); end
            ^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

This last error is because `webrick` has added a new keyword parameter to their `initialize` method that Sorbet doesn't know yet. This is easily fixable by forcing the `webrick` RBI file to be at `typed: false` by creating the following config:
```console
$ cat > sorbet/tapioca/config.yml
---
typed_overrides:
  "webrick": "false"
^D

$ rm sorbet/rbi/gems/webrick@1.7.0.rbi

$ bundle exec tapioca sync
Removing RBI files of gems that have been removed:

  Nothing to do.

Generating RBI files of gems that are added or updated:

  Requiring all gems to prepare for compiling...    Done

  Compiling webrick, this may take a few seconds...   Done (empty output)
  ++ Adding: sorbet/rbi/gems/webrick@1.7.0.rbi


All operations performed in working directory.
Please review changes and commit them.


$ bin/srb tc
No errors! Great job.
```

I have an idea that could make this process much more seamless but need to figure out if it will actually work.
