### ISSUE TITLE
Include a Changelog

### ISSUE THREAD

**Issue by hlascelles** [Shopify/tapioca#232]
Can this gem get a `CHANGELOG.md` please?

**Comment by paracycle** [comment]
We don't plan on adding one just yet, since we are still investigating the best API and mode of operation for the 1.0 release. Until then anything can change and the team does not have the free cycles to maintain a Changelog.

However, after a 1.0 release, we intend to keep a changelog or maintain proper release notes as part of the Github release.

**Comment by hlascelles** [comment]
OK, cheers :+1:
