### ISSUE TITLE
Incompatible with optional Bundler groups?

### ISSUE THREAD

**Issue by andyw8** [Shopify/tapioca#28]
Hi,

I'm trying Tapioca for the first time.  My project's Gemfile has some groups marked as `optional: true`, which seems to cause an issue when running `tapioca sync`:

```
Requiring all gems to prepare for compiling... /Users/awaite/.rvm/rubies/ruby-2.4.4/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:43:in
`block in for': Unable to find a spec satisfying spring-watcher-listen in the set. Perhaps the lockfile is corrupted? (Bundler::GemNotFound)
```
I've worked around it by temporarily commenting out those groups.

I can look into opening a PR to fix this, just wanted to log the issue first.

tapioca (0.2.5)
Bundler version 1.17.3
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin18]

**Comment by paracycle** [comment]
Hey @andyw8, thanks for the report, I was able to recreate that exact situation. 

It is a tricky problem since we try to load _all_ the gems in all the groups in the `Gemfile` so that we can generate an RBI file for all the possible gem dependencies. Right now, I am not sure how I can make Bundler skip ones that it cannot find, though, but I'll take a look.

Let me know if you have any ideas as well.

**Comment by andyw8** [comment]
I see there a `raise_on_missing` option here on `#for`, might be helpful:

https://github.com/bundler/bundler/blob/d9ea09defd07e9957ae782ab7960ebea92515c3c/lib/bundler/spec_set.rb#L15

**Comment by paracycle** [comment]
Indeed there is, but there are a few layers between that and the `setup(*groups).require(*groups)` call that we want to make which makes it impossible for us to pass the parameters we want to it. The alternative seems to be to replicate the behaviour of `setup` and/or `require`, but I'd rather not fork Bundler if we don't have to.

Let's think about this a bit more, maybe we can come up with a solution.
