### ISSUE TITLE
Generated RBI skipping included modules.

### ISSUE THREAD

**Issue by vaporyhumo** [Shopify/tapioca#357]
I'm building a gem where some of the classes are including sorbet modules, particularly `T::Props` and `T::Props::Constructor`; these modules are not getting included when running `bin/tapioca generate my_gem` on other projects.

Here is an extract of the file generated by `bin/parlour` when run on the gems directory:
```ruby
module Muina
  class Params
    include T::Props
    include T::Props::Constructor

    sig { params(params: T.any(T::Hash[T.untyped, T.untyped], ActionController::Parameters)).returns(T.attached_class) }
    def self.extract(params); end
  end
end
```

and here is the matching extract from the .rbi file being generated by tapioca:

```ruby
module Muina; end
class Muina::Params
  class << self
    def extract(params); end
  end
end
``` 

So I'm getting a lot of missing methods errors. Is there something I'm not getting right?

For now the way to go seems to be adding a script to copy the parlour's rbi file manually, and skipping it in tapioca (?).

I **can** provide the whole repo, and will gladly add any missing information upon request.

**Comment by paracycle** [comment]
Very early on in the project, we were not filtering any of the modules that are included/extended into constants, but then we ended up in situations where we generated things like:
```ruby
class Foo
  include T::Private::Final
end
```
which would fail type-checking since `T::Private::Final` was never declared in the Sorbet RBI file, since it is a private constant.

Because of this, we started filtering all module includes/extends where the module name starts with `"T::"`. You can see that happening [here](https://github.com/Shopify/tapioca/blob/e724ef9348710f1f8a20a9972a2afe080ad04459/lib/tapioca/compilers/symbol_table/symbol_generator.rb/#L372) and [here](https://github.com/Shopify/tapioca/blob/e724ef9348710f1f8a20a9972a2afe080ad04459/lib/tapioca/compilers/symbol_table/symbol_generator.rb/#L372)

Now, it seems we might have gone too far with that filtering, which is what is causing the problem you are having. On the other hand, [you can see that](https://github.com/sorbet/sorbet/blob/master/rbi/sorbet/tprops.rbi#L3-L4) those includes were never really designed to have been used outside of Sorbet runtime itself. 

So I am torn between how Tapioca should behave here.

**Comment by vaporyhumo** [comment]
Yeah I thought it would have been a special case for sorbet own modules. I do have a workaround, which is exposing a cli that copies the right rbi file to the proyect, so I'm not asking/needing any further changes. Tho just as you said maybe the filtering could be made a bit less strict.

Thanks for the answer, it's okay if you just close this issue. 👋
