### ISSUE TITLE
Parallelize RBI generation

### ISSUE THREAD

**Issue by KaanOzkan** [Shopify/tapioca#458]
Gem RBIs can be generated in forked processes. These child processes would send back `RBI::Tree` objects to the parent process which will be responsible for writing the objects to `.rbi` files.

**Comment by KaanOzkan** [comment]
DSL RBIs can also be generated in parallel

**Comment by vinistock** [comment]
I gave this a quick look to see if it would be easy to make it work and one problem I got blocked on was that `Bundler::StubSpecification` does not implement `_load`, which is used by DRb in order to share a Ruby object between different processes.

So, we have two alternatives: look into implementing `_load` ourselves or using a technique that doesn't need a queue, which is simpler but doesn't guarantee even distribution of the work load (i.e.: some processes will be idle while others will be processing for longer).
