### ISSUE TITLE
How to get ApplicationController to work?

### ISSUE THREAD

**Issue by Overload119** [Shopify/tapioca#512]
This is the output of `tapioca dsl ApplicationController`

```
# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl ApplicationController`.

# typed: true

class ApplicationController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule

  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::ActionText::ContentHelper
    include ::ActionText::TagHelper
    include ::Webpacker::Helper
    include ::ActionController::Base::HelperMethods
    include ::Pagy::Helpers
    include ::Pagy::Frontend
    include ::ApplicationHelper
    include ::AddressHelper
    include ::CampaignHelper
    include ::PostcardHelper
    include ::PostcardTemplateHelper
    include ::StaticHelper
    include ::UserHelper
    include ::LocalTimeHelper
    include ::ReactOnRails::Utils::Required
    include ::ReactOnRails::Helper
    include ::ReactOnRailsHelper
    include ::DeviseHelper
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
```

In all my controller though I'm unable to use the common methods such as `before_action` without getting a syntax error.

```
Method `before_action` does not exist on `T.class_of(Admin::LeadEnrichmentController)`
```

Can anyone shed some light on this?

**Comment by KaanOzkan** [comment]
`before_action` is a method on `AbstractController`, which is loaded by `ActionController` which is under `ActionPack`. As a result you should be able to see `before_action` defined in `actionpack@x.y.z.rbi` file after you generate gem RBIs for `actionpack` using:

`bundle exec tapioca gem actionpack`

You can take a look at which DSL's tapioca generates for from here: https://github.com/Shopify/tapioca/blob/main/manual/generators.md. In this case `before_action` is not covered by any of the DSL generators.

**Comment by Overload119** [comment]
Thanks for the explanation. 

Are you saying that since it isn't defined in the generator that there is no way to get this to work?
I have similar issues with other files, such as a model that has a `has_image_attached` function.

I'm able to fix these by manually editing the DSL file but I reckon this isn't what is meant to be done (as it will be overwritten by Tapioca anyway during the next generation).

**Comment by KaanOzkan** [comment]
I think first you should follow the migration document and get your RBIs in a good state https://github.com/Shopify/tapioca/wiki/Migrating-to-Tapioca

The main highlights being runing `bin/tapioca gem --all` and `bin/tapioca dsl` without any arguments. After this tapioca has done what it can regarding gem RBIs and DSLs that it supports. So at this point your initial error with `before_action` should hopefully be fixed.

Afterwards you might still have errors for methods that are dynamically defined that are causing errors. As you noted you can fix these inside `.rbi` files. We recommend adding new RBIs called `shims`, under `sorbet/rbi/shims`. Your example is a great shim. The class methods may be being mixed in dynamically and our ActiveSupport::Concern DSL generator isn't picking them up. You can create a `sorbet/rbi/shims/postcard.rbi` file and insert that content you have. You can also use shims to define methods, `def foo; end` when specific methods are causing Sorbet errors. Since these are in an RBI file they will be loaded during typechecking but won't be available in the application code.

Another thing to note is about "undefined" method errors for methods that are **statically** defined inside a gem.  In that case tapioca probably didn't load the correct file from the gem and therefore didn't import the method definition into an RBI. For those situations you can go the manual requires route https://github.com/Shopify/tapioca#manual-gem-requires.

Hope this helps.

**Comment by Overload119** [comment]
This does! Thank you.
