### ISSUE TITLE
Generating rbi files for current gem

### ISSUE THREAD

**Issue by hlascelles** [Shopify/tapioca#72]
`tapioca` works well for gem project dependencies - I am hoping to use it for a gem itself. There doesn't seem to be much in `sorbet`'s docs about how to go about doing that, so I am hoping `tapioca` could step in.

eg, if I have my own gem called `mygem`, I would like to do:

```bash
cd mygem
bundle exec tapioca local_rbi # This command doesn't exist yet
```

It would require all my gem's dependencies and walk them to get a baseline, then walk the code in this gem and output the difference to the gem's `rbi` folder.

Is that how Shopify handle things internally, or is there a technique I have missed to do this? 

I understand the answer may be "ask the sorbet team". People are asking similar questions like [this one](https://stackoverflow.com/questions/59024003/adding-sorbet-rbi-files-to-gems).

Thanks!

**Comment by KaanOzkan** [comment]
Am I understanding this right, you want `tapioca` to save RBI files in the gems themselves and not in the project that is depending on the gem?

`tapioca` the repo actually uses `tapioca` the gem to generate RBIs. To achieve this we use the steps outlined here https://github.com/Shopify/tapioca#usage

However, currently RBIs generated are stored within the project. Such as these RBIs for tapioca itself https://github.com/Shopify/tapioca/tree/master/sorbet/rbi/gems

**Comment by hlascelles** [comment]
Thank you for your reply! Not put the rbis in the other gems no... I'd like to put my gem's rbis in my my own gem's rbi folder. 

I could rephrase this question to say: I created a gem with no dependencies at all, and wish to publish it, and I would like other projects that use it to see its rbi declarations". As I understand it that means publishing the gem with an rbi folder (not a sorbet folder).

Can tapioca "make the rbi folder for my gem so I can publish it"?

I'd say if it can't now, it surely could with a small change. If it doesn't exist right now, would you accept a PR to add that feature?

**Comment by KaanOzkan** [comment]
Thanks for detailing it. I don't think tapioca can do that now and I think we'll be happy to have a contribution.

@paracycle can you confirm?

**Comment by paracycle** [comment]
@hlascelles We would be interested in such a contribution but to be honest, [`parlour`](https://github.com/AaronC81/parlour) might be a better tool for that, since [it is already doing exactly what you are asking for](https://github.com/AaronC81/parlour#generating-rbi-for-a-gem).

However, I should warn that `/rbi` folders exported from gems are currently a little problematic as they are not compatible with LSP mode yet ([see how we added a flag to disable it in `srb`](https://github.com/sorbet/sorbet/pull/3121)). So what we are doing inside `tapioca` is to generate an RBI with the signatures that are already inside your code, without you having to add another build step for your gem and without you having to include anything in your gem's `/rbi` folder. We feel that gives us more control over what is generated and how it is generated, instead of depending on RBI files exported by a gem which may or may not be up-to-date.

For all the reasons, I've detailed above, I will close this issue since we won't be working on it ourselves. If you find `parlour` lacking to do what you want and/or are not happy with `tapioca` generating RBi files with signatures automatically, feel free to add the functionality to do the RBI generation in a PR.

**Comment by hlascelles** [comment]
Thank you @paracycle, that does indeed look like what I was trying to find. I will check it out. But I also take on board your guidance as to "creating your own" rbi - I can well imagine being able to control it yourself can bring benefits.

In our particular case we have a monorepo, and a few root services refer to a folder of many internal private gems referred to in Gemfiles with `path:`. We were going to have an rbi folder in each gem - so we will have complete control as both the generator and consumer of the gem rbi files. I will find out how well it works...
