### ISSUE TITLE
Declaring monkey patch methods from a gem

### ISSUE THREAD

**Issue by hlascelles** [Shopify/tapioca#73]
I have an internal gem `fooer` that does this:

```ruby
class Foo
  def foome
  end
end

Hash.class_exec do
  def fooit
  end
end
```

When that gem is used by another project, and I run `tapioca` on that project, the `rbi` it produces for the `fooer` gem does include `Foo#foome` but not `Hash#fooit`. Running `srb` produces `rbi` that does include it.

I can believe how deeply complex this can all get. Is there a brief summary of how `tapioca` decides which constants and methods it "finds"? I am going to guess it is basically "all constants that are created in the code examined, and all of their methods". If so, i can see why the above would not show up.

If that is right (ish) would you accept a PR for the README that explicitly describes what to do about missed (monkey patch) methods?

**Comment by paracycle** [comment]
Hello @hlascelles, I can see why this happens and it is due to the particular way `tapioca` works. The problem is that the extension method on `Hash` is not seen by `tapioca` since if you load the code that you posted using Sorbet (which is what `tapioca` does under the covers) then it won't report that the `Hash` symbol was used in this file. Thus `tapioca` never processes `Hash` as a type to generate.

If you had something like:
```ruby
class Hash
  def self.barit
  end
end
```
then we would be generating the `barit` method. Actually, my guess is (I haven't tried this) that we would also generate the `fooit` method too, if `barit` definition was there as well.

If you have a better idea on how you can fix this, please feel free to open a PR. It would definitely be most welcome.
